feat: stringify msg keys value if not a string
pinojs/pino-pretty pull request #182
Opened 2021-05-03 09:39 UTC by e3tegi

2021-05-03 09:53 UTC, mcollina approved these changes
lgtm

2021-05-04 11:45 UTC, jsumners requested changes

2021-05-04 11:45 UTC, jsumners commented on lib/utils.js
> +  if (typeof log[messageKey] !== 'string') return colorizer.message(JSON.stringify(log[messageKey]))
```suggestion
  if (typeof log[messageKey] !== 'string') return colorizer.message(stringifySafe(log[messageKey]))
```

2021-05-26 13:09 UTC, mcollina commented
Close with no activity.

2021-05-26 13:09 UTC, closed without merging