Add support for custom prettifiers on the metadata
pinojs/pino-pretty pull request #283
Opened 2021-12-13 16:34 UTC by airhorns

So folks can prettify the pid, logger name, or hostname as they see fit!

2021-12-13 16:51 UTC, mcollina approved these changes
lgtm

2021-12-13 17:11 UTC, mcollina commented
CI is failing

2021-12-13 18:13 UTC, jsumners requested changes
Please update the documentation showing how to use this feature.

2021-12-13 18:13 UTC, jsumners commented on lib/utils.js
> +function prettifyMetadata ({ log, prettifiers = {} }) {
Please document this in the docblock.

2021-12-13 22:23 UTC, airhorns commented
Updated with docs and the coverage target

2021-12-14 10:15 UTC, mcollina approved these changes
lgtm

2021-12-14 13:34 UTC, jsumners requested changes

2021-12-14 13:34 UTC, jsumners commented on lib/utils.js
> + * @param {object} input.log The log that may or may not contain metadata to be prettified
Please re-wrap this as it was before and restore the punctuation.

2021-12-14 16:02 UTC, jsumners approved these changes
Looks good to me.

2021-12-14 17:34 UTC, merged