feat: allow prettifier for messageKey as number
pinojs/pino-pretty pull request #302
Opened 2022-02-15 16:16 UTC by LRipi

Add support for messageKey as a number.
PR related to issue #181

2022-02-15 16:17 UTC, doums commented
Best PR ever made 🥇

2022-02-15 16:19 UTC, doums approved these changes

2022-02-15 16:22 UTC, Mheaus approved these changes

2022-02-15 20:50 UTC, mcollina requested changes
Can you please add a unit test?

2022-08-17 10:51 UTC, mcollina commented
Closing for no activity.

2022-08-17 10:51 UTC, closed without merging