feat: dont print escape backslash on strings containing escaped backslashes
pinojs/pino-pretty pull request #401
Opened 2023-02-13 01:51 UTC by ademarsj

Closes #378 , I'm not pretty sure about the way that I made it, but I think creating a function to do exactly that line of code is unnecessary.

2023-02-13 14:55 UTC, mcollina commented
Could you fix it in Node v14? Otherwise it would need to wait until we bump the major to drop node v14.

2023-02-13 15:33 UTC, ademarsj commented
> 

Working on that.

2023-02-13 16:24 UTC, ademarsj commented
Done, passing through all tests.

2023-02-15 07:48 UTC, mcollina approved these changes
lgtm

2023-02-15 15:23 UTC, jsumners requested changes

2023-02-15 15:23 UTC, jsumners commented on lib/utils.js
>    } else {
```suggestion
    result += eol
    // Avoid printing the escape character on escaped backslashes.
    result = result.replace(/\\\\/gi, '\\')
  } else {
```

2023-02-16 00:46 UTC, ademarsj commented
Grammar issues fixed.

2023-02-17 13:00 UTC, jsumners approved these changes

2023-02-17 13:25 UTC, merged

2023-02-17 17:18 UTC, ntzm commented
Thanks 🎉