Add a colorizeObjects option to disable object colorization
pinojs/pino-pretty pull request #403
Opened 2023-02-20 15:29 UTC by Avaq

This allows log parsers that can detect JSON at the end of a log line to do so without being thrown off by ANSI colors.

Specifically, we're using Pino + Pino Pretty with Papertrail. Papertrail has [this feature](https://www.papertrail.com/help/json-search/) where they parse JSON at the end of a line. But their JSON parser fails to do so when that JSON is surrounded by ANSI codes.

I could disable colorization altogether, but Papertrail does nicely present ANSI colored logs in their web-UI, so I don't want to do that.

I've sent the Papertrail devs a message, because I think it'd be nicest if it were solved on their side, but as a plan B, and for the time being, this is the next best solution.

2023-02-20 15:53 UTC, jsumners commented
I'm confused. Why are you sending the output of `pino-pretty` to a log collector?

2023-02-20 16:18 UTC, Avaq commented
We don't need to merge this. I can just use the fork for now and see what comes out of the Papertrail support ticket. Also, I understand that this change doesn't really align with the JSON logger philosophy: That disabling the colors on objects is really just muddying the separation of data and presentation (we're using some part of the presentation as data).

2023-02-20 16:40 UTC, Avaq commented
For reference, here's what the 3 situations look like in Papertrail:

- **Colors disabled** - JSON gets parsed, but no colors
  ![latest-screenshot](https://user-images.githubusercontent.com/1217745/220158171-057bfa94-cd05-4737-8aaa-92ffd4b05a05.png)
- **Colors enabled** - JSON not parsed, but colors
  ![latest-screenshot](https://user-images.githubusercontent.com/1217745/220158430-47bbb3ad-3349-4a98-9e94-b7e7be4d1f4c.png)
- **Colors enabled, but disabled for objects** - JSON gets parsed, and colors
  ![latest-screenshot](https://user-images.githubusercontent.com/1217745/220158519-447ac070-3c3a-4683-8f3d-0a5b1008ae2d.png)

And when sending it unformatted JSON logs, it'll just show the whole JSON object printed as shown in the screenshots, without any way for the user to control how it's formatted.

I don't know if this issue is worth solving here. I just opened the PR because I had the code ready, and it might be useful to some folks.

2023-02-21 09:48 UTC, mcollina approved these changes
lgtm

2023-02-21 09:49 UTC, mcollina commented
(Note that you shouldn't really do what you are doing for the optimal production setup)

2023-02-21 23:00 UTC, mcollina commented
@jsumners PTAL

2023-02-21 23:22 UTC, jsumners requested changes
Full documentation is missing. I would imagine it should go between the current lines 59 and 60 of the readme.

2023-02-24 13:42 UTC, Avaq commented
@jsumners I [pushed](https://github.com/pinojs/pino-pretty/compare/8554b4a82bbb9dddd0b22f8e6ad16b06d4af1164..5ef89c78532d04d635d83a070ad5a355bf31e9ba) a version with updated docs. Sorry I missed this earlier.

2023-02-24 13:44 UTC, Avaq commented
I also heard back from Papertrail. They say it'll take a lot to fix on their end, and they proposed that a change to pino-pretty might be the easiest.

2023-02-24 13:50 UTC, jsumners commented
> I also heard back from Papertrail. They say it'll take a lot to fix on their end, and they proposed that a change to pino-pretty might be the easiest.

Of course they will put the onus on the open source community. They have zero incentive to improve their product.

2023-02-24 13:51 UTC, jsumners approved these changes

2023-02-24 13:53 UTC, merged