Support objects in options.customColors
pinojs/pino-pretty pull request #487
Opened 2024-01-18 19:10 UTC by kindagonzo

Documentation notes that options.customColors can be either a string or object but objects are not currently supported in the code.
From index.d.ts:
  /**
   * Change the level colors to an user custom preset.
   *
   * Can be a CSV string in 'level_name:color_value' format or an object.
   * Also supports 'default' as level_name for fallback color.
   *
   * @example ( CSV ) customColors: 'info:white,some_level:red'
   * @example ( Object ) customColors: { info: 'white', some_level: 'red' }
   */
  customColors?: string|object;

This change permits either strings or objects to be used.

2024-01-19 13:58 UTC, mcollina requested changes
Thanks for opening a PR! Can you please add a unit test?

2024-01-24 13:46 UTC, kindagonzo commented
> Thanks for opening a PR! Can you please add a unit test?

Sure. I checked around in the test folder but I can't seem to find any tests referencing that function. Where would you like me to add a test?

2024-01-25 12:40 UTC, mcollina commented
You can test it via `prettyFactory` (https://github.com/pinojs/pino-pretty/blob/9d89a596f492eb2efee1632f54be9bc9b93356f4/test/basic.test.js#L526) or add a new file altogether.

2024-01-25 15:59 UTC, kindagonzo commented
Can you help me out? I added the test and can run the suite fine with npm run test or npm run ci:
![PinoPretty Success](https://github.com/pinojs/pino-pretty/assets/97182017/a74d37b0-b6d1-4f2c-b742-fa97374e34e7)

However, the pre-commit hook fails:
![PinoPretty Fail](https://github.com/pinojs/pino-pretty/assets/97182017/3bb15ed8-e898-4a58-a2a3-dd9ebb79b828)

Any idea why?

2024-01-25 16:12 UTC, kindagonzo commented
It seems to be a transient issue. I ran it a few times and was finally able to commit.

2024-01-26 18:35 UTC, mcollina approved these changes
lgtm

2024-03-20 13:48 UTC, merged