fix: add injection lacking arguments of customPrettifiers
pinojs/pino-pretty pull request #501
Opened 2024-03-24 18:00 UTC by pasha-vuiko

resolves #500

2024-03-25 13:25 UTC, mcollina requested changes
Thanks for opening a PR! Can you please add a unit test?

2024-03-25 16:29 UTC, pasha-vuiko commented
> Thanks for opening a PR! Can you please add a unit test?

done

2024-03-31 13:29 UTC, mcollina approved these changes
lgtm

2024-03-31 13:35 UTC, jsumners requested changes

2024-03-31 13:35 UTC, jsumners commented on lib/utils/prettify-metadata.test.js
>  const context = {
```suggestion
const tap = require('tap')
const prettifyMetadata = require('./prettify-metadata')
const getColorizer = require('../colors')
const context = {
```

2024-03-31 13:55 UTC, pasha-vuiko commented on lib/utils/prettify-metadata.test.js
>  const context = {
fixed

2024-04-14 13:46 UTC, pasha-vuiko commented
@jsumners could you re-review please?

2024-06-09 17:32 UTC, pasha-vuiko commented
@jsumners hey 👋, what about re-review?🙂

2024-06-09 19:37 UTC, jsumners approved these changes

2024-06-09 19:38 UTC, merged